create table students (
  id bigint generated by default as identity primary key,
  roll_no varchar(32) not null unique,
  full_name varchar(200) not null
);

create table periods (
  id bigint generated by default as identity primary key,
  name varchar(80) not null
);

create table attendance (
  id bigint generated by default as identity primary key,
  attendance_date date not null,
  status varchar(20) not null,
  student_id bigint not null,
  period_id bigint,
  constraint fk_attendance_student foreign key (student_id) references students(id),
  constraint fk_attendance_period foreign key (period_id) references periods(id)
);

create index idx_attendance_date on attendance(attendance_date);
